name: Semver PR Label Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  run_semver_pr_label_check:
    uses: ./.github/workflows/semver_pr_label_check.yml
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}